### ISSUE TITLE
Add setting the number of buckets

### ISSUE THREAD

**Issue by orloffv** [ydb-platform/ydb-go-sdk-prometheus#4]
I can't use this library, because my system of collect metrics does't support more than 51 buckets
https://github.com/ydb-platform/ydb-go-sdk-prometheus/blob/master/types.go#L20

**Comment by asmyasnikov** [comment]
From v0.12.0:
* Add `WithTimerBuckets` option for redefine default timer buckets
* Refactored internal bench over native sdk
* Added internal bench over `database/sql` API
